- id:    auto-unlock
  alias: Auto Unlock
  trigger:
  - platform:  state
    entity_id: binary_sensor.walkway_jphone_presence
    from:      'off'
    to:        'on'
  action:
  - service:   lock.unlock
    entity_id: lock.frontdoor

- id: speaker-monitor
  alias: Speaker Monitor
  trigger:
    - platform:  state
      entity_id: media_player.portal_to_hell
      to:        'unavailable'
    - platform:  state
      entity_id: media_player.portal_to_hell
      to:        'standby'
  condition:
    condition: state
    entity_id: light.jasco_products_45853_15671900_on_off
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.jasco_products_45853_15671900_on_off