
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

homeassistant:
  latitude:  !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_ele

# Text to speech
tts:
  - platform: google_translate

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key

zha:
  database_path: /config/zigbee.db

octoprint:
  - host: !secret octoprint_host
    api_key: !secret octoprint_key
    name: PrusaMK3s
    bed: true
    number_of_tools: 1
    sensors:
      monitored_conditions:
        - Current State
        - Temperatures

automation: !include automations.yaml

light:
  - platform: template
    lights:
      house_lights:
        friendly_name: House Lights
        turn_on:
          service: light.turn_on
          entity_id:
            - light.jasco_products_45857_b01a2100_level_on_off
            - light.ledvance_br30_rgbw_276b0600_level_light_color_on_off
            - light.ledvance_br30_rgbw_b7620600_level_light_color_on_off
            - light.nook_light_level_light_color_on_off
        turn_off:
          service: light.turn_off
          entity_id:
            - light.jasco_products_45857_b01a2100_level_on_off
            - light.ledvance_br30_rgbw_276b0600_level_light_color_on_off
            - light.ledvance_br30_rgbw_b7620600_level_light_color_on_off
            - light.nook_light_level_light_color_on_off

# automation: !include automations.yaml
automation: !include_dir_merge_list automations/
script:     !include scripts.yaml
group:      !include groups.yaml
scene:      !include scenes.yaml
zone:       !include zones.yaml